### PR TITLE
Use pre-existing clip_vision models

### PR DESCRIPTION
**Pull request by cdb-boop**
This does not make use of the downloaded transformers models in the transformers cache.

### CODE REVIEW

**Comment by kijai** [comment]
This still expects whole model directory though, not single files?

**Comment by cdb-boop** [comment]
Only for 2.

Line 94 & 95 of nodes.py

`SDXL_CLIP1_PTH = os.path.split(folder_paths.get_full_path("clip_vision", sdxl_clip1))[0]`

`SDXL_CLIP2_CKPT_PTH = folder_paths.get_full_path("clip_vision", sdxl_clip2)`

I thought SDXL_CLIP2_CKPT_PTH only expects one model file... is that not correct? I thought that's how IP_Adapter_Plus handles it. I guess you can change 2 to a folder like I did for 1 if you prefer that (change line 95 to match 94).

**Comment by kijai** [comment]
SDXL_CLIP2_CKPT_PTH indeed works with the .bin file, but not with .safetensors.
SDXL_CLIP1_PTH needing whole folder is pretty awkward, I think we should look into way to include the configs and load the weights from .safetensors instead?

**Comment by cdb-boop** [comment]
> SDXL_CLIP1_PTH needing whole folder is pretty awkward, I think we should look into way to include the configs and load the weights from .safetensors instead?

Yeah, it isn't ideal but it seems like a transformers issue. I don't think it's that bad if you just clearly instructed users in the README. However, if you want an alternative, I think there could be a way to use symbolic links.

**Comment by kijai** [comment]
Ok I think I figured it out finally, the vision part is not even used. I got it to load the CLIPs from the initial SDXL checkpoint instead, so no need for extra models at all now, I'll finally close this PR. Thank you for the input nevertheless!

**Pull request closed without merging**
